### ISSUE TITLE
wrong output for unknown commands

### ISSUE THREAD

**Issue by ghost** [D0han/mockmaker#2]
hi,

let's assume that unknown_command is not available in the system:

``` shell
[brand0m@helium mockmaker]$ unknown_command
bash: unknown_command: command not found
[brand0m@helium mockmaker]$ 
```

then let's try to mock that (yes, I know it's pointless to mock something which
is really not available)

``` shell
[brand0m@helium mockmaker]$ ./mock unknown_command

exit code: 127
[brand0m@helium mockmaker]$
```

finally let's try to run mocked unknown_command:

``` shell
[brand0m@helium mockmaker]$ ./mocks/unknown_command 

./mock: line 11: unknown_command: command not found
[brand0m@helium mockmaker]$ 
```

are you planning to unify output for such a cases?

**Comment by D0han** [comment]
I am not sure, what is the reasonable outcome for such operation.
I guess it could fail on mock creation step, if there is no such command.

**Comment by ghost** [comment]
yeah, that would be even better solution
